from learn_pratice.apps.blog.models.mysql.article import *
from learn_pratice.apps.blog.models.mysql.article_sort import *
from learn_pratice.apps.blog.models.mysql.blog import *
from learn_pratice.apps.blog.models.mysql.photo import *
from learn_pratice.apps.blog.models.mysql.photo_sort import *
from learn_pratice.apps.blog.models.mysql.secret_message import *
from learn_pratice.apps.blog.models.mysql.system_message import *
from learn_pratice.apps.blog.models.mysql.user_attention import *
from learn_pratice.apps.blog.models.mysql.user_info import *
from learn_pratice.apps.blog.models.mysql.user_stay_message import *
