# Generated by Django 3.0.5 on 2021-03-24 16:34

from django.db import migrations, models
import django.db.models.deletion
import learn_pratice.apps.mongo_blog.models.mongodb.user
import learn_pratice.apps.mongo_blog.utils.tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('blog_keyword', models.CharField(max_length=255, verbose_name='博客关键字')),
                ('blog_description', models.CharField(max_length=255, verbose_name='博客描述')),
                ('blog_name', models.CharField(max_length=36, verbose_name='博客名称')),
                ('blog_title', models.CharField(max_length=128, verbose_name='博客标题')),
            ],
        ),
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('system_id', models.AutoField(primary_key=True, serialize=False, verbose_name='系统通知')),
                ('send_id', models.IntegerField(verbose_name='接受者ID')),
                ('group_id', models.IntegerField(verbose_name='用户组ID')),
                ('send_default', models.BooleanField(default=False, verbose_name='1时发送所有用户，0时则不采用')),
                ('system_topic', models.CharField(max_length=100, verbose_name='通知内容')),
                ('system_content', models.TextField(max_length=255, verbose_name='通知内容')),
            ],
        ),
        migrations.CreateModel(
            name='UserStayMessage',
            fields=[
                ('stay_id', models.AutoField(primary_key=True, serialize=False, verbose_name='留言表')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('stay_user_id', models.IntegerField(verbose_name='留言者ID')),
                ('message_content', models.TextField(max_length=255, verbose_name='留言内容')),
                ('message_stay_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30, unique=True, verbose_name='')),
                ('nice_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='昵称')),
                ('phone_num', models.IntegerField(default=0, verbose_name='手机号')),
                ('identity_card', models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证号')),
                ('user_discription', models.CharField(blank=True, max_length=256, null=True, verbose_name='自我描述')),
                ('photo', models.ImageField(default='default.jpg', upload_to=learn_pratice.apps.mongo_blog.utils.tools.user_directory_path, verbose_name='头像')),
                ('blog', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mongo_blog.Blog')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserAttention',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户关注表')),
                ('attention_id', models.IntegerField(verbose_name='关注ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mongo_blog.UserInfo', verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[learn_pratice.apps.mongo_blog.models.mongodb.user.UnicodeUsernameValidator()], verbose_name='username')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('nice_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='昵称')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('phone_num', models.IntegerField(default=0, verbose_name='手机号')),
                ('identity_card', models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证号')),
                ('introduce', models.CharField(blank=True, max_length=256, null=True, verbose_name='自我描述')),
                ('photo', models.ImageField(default='default.jpg', upload_to=learn_pratice.apps.mongo_blog.utils.tools.user_directory_path, verbose_name='头像')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('blog', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mongo_blog.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='SecretMessage',
            fields=[
                ('secret_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户私信表')),
                ('receive_id', models.IntegerField(verbose_name='收信者ID')),
                ('message_topic', models.CharField(max_length=100, verbose_name='私信标题')),
                ('message_content', models.TextField(max_length=255, verbose_name='私信内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mongo_blog.UserInfo', verbose_name='发信者ID')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSort',
            fields=[
                ('sort_img_id', models.AutoField(primary_key=True, serialize=False, verbose_name='相册ID')),
                ('sort_img_name', models.CharField(max_length=20, verbose_name='相册名')),
                ('top_pic_src', models.IntegerField(verbose_name='封面图片ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mongo_blog.UserInfo', verbose_name='所属用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='相片ID')),
                ('photo_name', models.CharField(max_length=100, verbose_name='相片名称')),
                ('photo_src', models.ImageField(blank=True, null=True, upload_to=learn_pratice.apps.mongo_blog.utils.tools.user_directory_path, verbose_name='图片路径')),
                ('user_id', models.IntegerField(verbose_name='所属用户ID')),
                ('photo_sort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mongo_blog.PhotoSort')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSort',
            fields=[
                ('sort_article_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='文章分类表')),
                ('sort_article_name', models.CharField(max_length=60, verbose_name='分类名称')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mongo_blog.UserInfo', verbose_name='分类所属用户')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章表')),
                ('article_name', models.CharField(max_length=100, verbose_name='文章名称')),
                ('article_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('article_click', models.IntegerField(default=0, verbose_name='查看人数')),
                ('username', models.CharField(max_length=150, verbose_name='所属用户')),
                ('article_type', models.BooleanField(default=True, verbose_name='文章内容公开')),
                ('article_content', models.TextField(verbose_name='文章内容')),
                ('article_is_up', models.BooleanField(default=True, verbose_name='是否置顶')),
                ('article_support', models.BooleanField(default=True, verbose_name='是否博主推荐')),
                ('article_sort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mongo_blog.ArticleSort', verbose_name='所属分类')),
            ],
        ),
    ]
